// Mitä actioneita (redux) on olemassa

export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const ADD_GAME = 'ADD_GAME';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';
export const DELETE_GAME = 'DELETE_GAME';
export const EDIT_GAME = 'EDIT_GAME';
export const FETCH_GAMES = 'FETCH_GAMES';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_HOUSES = 'FETCH_HOUSES';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAILURE = 'FETCH_HOUSES_FAILURE';
export const CLEAN_HOUSE = 'CLEAN_HOUSE';
export const CLEAN_HOUSE_SUCCESS = 'CLEAN_HOUSE_SUCCESS';
export const CLEAN_HOUSE_FAILURE = 'CLEAN_HOUSE_FAILURE';

export const SHOW_HOUSE = 'SHOW_HOUSES';
export const SHOW_HOUSE_SUCCESS = 'SHOW_HOUSE_SUCCESS';
export const SHOW_HOUSE_FAILURE = 'SHOW_HOUSE_FAILURE';
